import { FieldOption } from "@/tipos/plataforma";

export const estadosBrasil: FieldOption[] = [
  { label: "Acre", value: "Acre" },
  { label: "Alagoas", value: "Alagoas" },
  { label: "Amapa", value: "Amapa" },
  { label: "Amazonas", value: "Amazonas" },
  { label: "Bahia", value: "Bahia" },
  { label: "Ceara", value: "Ceara" },
  { label: "Distrito Federal", value: "Distrito Federal" },
  { label: "Espirito Santo", value: "Espirito Santo" },
  { label: "Goias", value: "Goias" },
  { label: "Maranhao", value: "Maranhao" },
  { label: "Mato Grosso", value: "Mato Grosso" },
  { label: "Mato Grosso do Sul", value: "Mato Grosso do Sul" },
  { label: "Minas Gerais", value: "Minas Gerais" },
  { label: "Para", value: "Para" },
  { label: "Paraiba", value: "Paraiba" },
  { label: "Parana", value: "Parana" },
  { label: "Pernambuco", value: "Pernambuco" },
  { label: "Piaui", value: "Piaui" },
  { label: "Rio de Janeiro", value: "Rio de Janeiro" },
  { label: "Rio Grande do Norte", value: "Rio Grande do Norte" },
  { label: "Rio Grande do Sul", value: "Rio Grande do Sul" },
  { label: "Rondonia", value: "Rondonia" },
  { label: "Roraima", value: "Roraima" },
  { label: "Santa Catarina", value: "Santa Catarina" },
  { label: "Sao Paulo", value: "Sao Paulo" },
  { label: "Sergipe", value: "Sergipe" },
  { label: "Tocantins", value: "Tocantins" },
];

export const estadosBrasilSiglas: FieldOption[] = [
  { label: "AC", value: "AC" },
  { label: "AL", value: "AL" },
  { label: "AP", value: "AP" },
  { label: "AM", value: "AM" },
  { label: "BA", value: "BA" },
  { label: "CE", value: "CE" },
  { label: "DF", value: "DF" },
  { label: "ES", value: "ES" },
  { label: "GO", value: "GO" },
  { label: "MA", value: "MA" },
  { label: "MT", value: "MT" },
  { label: "MS", value: "MS" },
  { label: "MG", value: "MG" },
  { label: "PA", value: "PA" },
  { label: "PB", value: "PB" },
  { label: "PR", value: "PR" },
  { label: "PE", value: "PE" },
  { label: "PI", value: "PI" },
  { label: "RJ", value: "RJ" },
  { label: "RN", value: "RN" },
  { label: "RS", value: "RS" },
  { label: "RO", value: "RO" },
  { label: "RR", value: "RR" },
  { label: "SC", value: "SC" },
  { label: "SP", value: "SP" },
  { label: "SE", value: "SE" },
  { label: "TO", value: "TO" },
];

export const cidadesSugeridas: FieldOption[] = [
  { label: "Bom Jesus da Lapa", value: "Bom Jesus da Lapa" },
  { label: "Salvador", value: "Salvador" },
  { label: "Barreiras", value: "Barreiras" },
  { label: "Brasilia", value: "Brasilia" },
  { label: "Feira de Santana", value: "Feira de Santana" },
  { label: "Guanambi", value: "Guanambi" },
  { label: "Sao Paulo", value: "Sao Paulo" },
];

export const bairrosBomJesusDaLapa: FieldOption[] = [
  { label: "Centro", value: "Centro" },
  { label: "Amaralina", value: "Amaralina" },
  { label: "Barrinha", value: "Barrinha" },
  { label: "Beira Rio", value: "Beira Rio" },
  { label: "Cavalhadas", value: "Cavalhadas" },
  { label: "Joao Paulo II", value: "Joao Paulo II" },
  { label: "Jurema", value: "Jurema" },
  { label: "Guarani", value: "Guarani" },
  { label: "Lagoa Grande", value: "Lagoa Grande" },
  { label: "Loteamento Mirante da Lapa", value: "Loteamento Mirante da Lapa" },
  { label: "Loteamento Nova Lapa", value: "Loteamento Nova Lapa" },
  { label: "Loteamento Sao Conrado", value: "Loteamento Sao Conrado" },
  { label: "Magalhaes Neto", value: "Magalhaes Neto" },
  { label: "Maravilha I", value: "Maravilha I" },
  { label: "Maravilha II", value: "Maravilha II" },
  { label: "Maribondo", value: "Maribondo" },
  { label: "Nova Brasilia", value: "Nova Brasilia" },
  { label: "Parque Verde", value: "Parque Verde" },
  { label: "Santa Luzia", value: "Santa Luzia" },
  { label: "Sao Gotardo", value: "Sao Gotardo" },
  { label: "Sao Joao", value: "Sao Joao" },
  { label: "Mirante", value: "Mirante" },
];
