export const configuracaoPortal = {
  nome: "Visite Lapa",
  siteUrl: "https://visitelapa.com.br",
  cidade: "Bom Jesus da Lapa - BA",
  email: "contato@visitelapa.com.br",
  whatsappNumero: "5577992116008",
  whatsappExibicao: "(77) 99211-6008",
  instagramUrl: "https://instagram.com/visitelapa",
  instagramHandle: "@visitelapa",
  endereco: "Centro, Bom Jesus da Lapa - BA",
  usernamesNegociosProibidos: [
    "admin",
    "dashboard",
    "login",
    "contato",
    "cadastro",
    "api",
    "blog",
    "eventos",
    "hoteis",
    "negocios",
    "restaurantes",
    "cidades",
    "bairros",
    "categorias",
    "tags",
    "sobre",
    "suporte",
    "ajuda",
  ],
} as const;
