create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create table if not exists public.estados (
  id bigint generated by default as identity primary key,
  sigla text not null unique,
  nome text not null,
  slug text not null unique,
  ordem integer not null default 1,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint estados_sigla_check check (char_length(sigla) = 2)
);

create table if not exists public.cidades (
  id bigint generated by default as identity primary key,
  estado_id bigint not null references public.estados(id) on delete restrict,
  nome text not null,
  slug text not null unique,
  descricao text not null default '',
  ordem integer not null default 1,
  status text not null default 'publicado',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.bairros (
  id bigint generated by default as identity primary key,
  cidade_id bigint not null references public.cidades(id) on delete restrict,
  nome text not null,
  slug text not null unique,
  descricao text not null default '',
  ordem integer not null default 1,
  status text not null default 'publicado',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists cidades_estado_id_idx on public.cidades (estado_id);
create index if not exists cidades_ordem_idx on public.cidades (ordem);
create index if not exists bairros_cidade_id_idx on public.bairros (cidade_id);
create index if not exists bairros_ordem_idx on public.bairros (ordem);

drop trigger if exists set_estados_updated_at on public.estados;
create trigger set_estados_updated_at
before update on public.estados
for each row
execute function public.set_updated_at();

drop trigger if exists set_cidades_updated_at on public.cidades;
create trigger set_cidades_updated_at
before update on public.cidades
for each row
execute function public.set_updated_at();

drop trigger if exists set_bairros_updated_at on public.bairros;
create trigger set_bairros_updated_at
before update on public.bairros
for each row
execute function public.set_updated_at();

insert into public.estados (sigla, nome, slug, ordem)
values
  ('BA', 'Bahia', 'bahia', 1),
  ('DF', 'Distrito Federal', 'distrito-federal', 2),
  ('SP', 'Sao Paulo', 'sao-paulo', 3)
on conflict (sigla) do update
set
  nome = excluded.nome,
  slug = excluded.slug,
  ordem = excluded.ordem,
  updated_at = timezone('utc'::text, now());

insert into public.cidades (estado_id, nome, slug, descricao, ordem, status)
select
  e.id,
  'Bom Jesus da Lapa',
  'bom-jesus-da-lapa',
  '',
  1,
  'publicado'
from public.estados e
where e.sigla = 'BA'
on conflict (slug) do update
set
  estado_id = excluded.estado_id,
  nome = excluded.nome,
  descricao = excluded.descricao,
  ordem = excluded.ordem,
  status = excluded.status,
  updated_at = timezone('utc'::text, now());

insert into public.bairros (cidade_id, nome, slug, descricao, ordem, status)
select
  c.id,
  bairro.nome,
  bairro.slug,
  '',
  bairro.ordem,
  'publicado'
from public.cidades c
cross join (
  values
    ('Centro', 'centro', 1),
    ('Amaralina', 'amaralina', 2),
    ('Barrinha', 'barrinha', 3),
    ('Beira Rio', 'beira-rio', 4),
    ('Cavalhadas', 'cavalhadas', 5),
    ('Joao Paulo II', 'joao-paulo-ii', 6),
    ('Jurema', 'jurema', 7),
    ('Guarani', 'guarani', 8),
    ('Lagoa Grande', 'lagoa-grande', 9),
    ('Loteamento Mirante da Lapa', 'loteamento-mirante-da-lapa', 10),
    ('Loteamento Nova Lapa', 'loteamento-nova-lapa', 11),
    ('Loteamento Sao Conrado', 'loteamento-sao-conrado', 12),
    ('Magalhaes Neto', 'magalhaes-neto', 13),
    ('Maravilha I', 'maravilhas-i', 14),
    ('Maravilha II', 'maravilhas-ii', 15),
    ('Maribondo', 'maribondo', 16),
    ('Nova Brasilia', 'nova-brasilia', 17),
    ('Parque Verde', 'parque-verde', 20),
    ('Santa Luzia', 'santa-luzia', 27),
    ('Sao Gotardo', 'sao-gotardo', 28),
    ('Sao Joao', 'sao-joao', 29),
    ('Mirante', 'mirante', 30)
) as bairro(nome, slug, ordem)
where c.slug = 'bom-jesus-da-lapa'
on conflict (slug) do update
set
  cidade_id = excluded.cidade_id,
  nome = excluded.nome,
  descricao = excluded.descricao,
  ordem = excluded.ordem,
  status = excluded.status,
  updated_at = timezone('utc'::text, now());
